services:
  load_balancer:
    build:
      context: .
      dockerfile: load_balancer/Dockerfile
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net1

  server:
    build: ./server
    image: server-img
    networks:
      - net1

networks:
  net1:
    name: net1
